### PR TITLE
Fix docs site

### LINKED ISSUE #6: docs site not working
We lost some CSS dependencies in the shuffle to remove the bower dependency, see #3. 

Suggested solution:
* use necessary bower packages as dev dependencies only

### PR DESCRIPTION
**Pull request by romulomachado**
Installed some missing dependencies and got rid of `ember-markdown-section` (very old dependency (2+ years without updates)).

[Closes #6]

### CODE REVIEW

**Comment by brenna** [comment]
Is there a good replacement for `ember-markdown-section`? it's a PITA to update docs without being about to use markdown.

**Comment by romulomachado** [comment]
Not that I could find. None of them accept template blocks and I personally think inline strings are not great in this case. The best I could find was [ember-remarkable](https://github.com/johnotander/ember-remarkable):

```hbs
<div>
  {{md-text
    text = "
# Hello world

Note that you have to unindent
the multiline `text` content.
    "
  }}
</div>
```
But that's kinda ugly, IMO.

**Comment by brenna** [comment]
Ok, too bad. Willing to let the markdown go tho for the vast other improvements!

**Review by brenna — APPROVED** [review]

**Comment by brenna** [comment]
🙌

**Comment by romulomachado** [comment]
Merged and deployed, btw!

screen shot 2017-07-19 at 1 24 06 pm

**Pull request merged**
