### PR TITLE
[wip] Kill Bil— I mean, Bower. And other stuff.

### LINKED ISSUE #2: update to shed v1.2.0
[v1.2.0](https://github.com/tedconf/shed-css/releases/tag/v1.2.0) includes cursor support. (tedconf/shed-css#3)

- [ ] update shed dependency

### PR DESCRIPTION
**Pull request by romulomachado**
kill bower

This PR:

- [x] Removes `bower.json` dependencies and moves them to npm
- [x] Updates dependencies
- [x] Replaces jshint with eslint
- [x] Updates config

[Closes #2 maybe?]

I need help testing it. Suite is all passing, but I'm not sure I've done everything needed.

### CODE REVIEW

**Comment by brenna** [comment]
@romulomachado can you try installing this version on a new ember project and ensure shed is available?  I'm not sure how to test this side of an addon in the suite. If you know how, you can definitely add a test that does that.  shed.css wasn't being used as an npm dependency before since `app.import` didn't work with css files in node modules at the time of authoring. Has that changed?

**Comment by brenna** [comment]
Oh, also for testing this out before the PR is merged, `npm link` is a handy way to use your local repo instead of what's published on npm or github.

**Comment by romulomachado** [comment]
It's still impossible to import the css file from node_modules, so ¯\\\_(ツ)\_/¯.

**Comment by brenna** [comment]
😭 dang it.

**Comment by romulomachado** [comment]
`ember install ember-ted-shed` isn't working atm either since `shed-css` isn't on bower anymore.

**Comment by brenna** [comment]
aw crap, we will have to find a workaround. i would rather not have the bower funny business anyhow. maybe this is worth looking into? https://www.npmjs.com/package/ember-cli-node-assets either that or a deep dive into broccoli (which was a dead end last time i tried, sadly).

**Comment by romulomachado** [comment]
whooo, that sounds like a solution!

**Comment by brenna** [comment]
you gonna take a crack at it?

**Comment by romulomachado** [comment]
yep, doing it right now

**Comment by brenna** [comment]
omg yayyy! thank you for cleaning this up!

**Comment by romulomachado** [comment]
Did my last testing here, 

```
  e install git+ssh://git@github.com:tedconf/ember-ted-shed#update-dependencies
``` 

works fine. :raised_hands:

**Comment by brenna** [comment]
awesome, that's good enough for me.

**Pull request merged**
